# Generated by Django 2.0 on 2019-07-01 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20190629_0311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date account created'),
        ),
    ]
